if(NOT DEFINED CLI OR NOT DEFINED SOURCE_DIR OR NOT DEFINED TEST_OUTPUT_DIR)
    message(FATAL_ERROR "CLI, SOURCE_DIR and TEST_OUTPUT_DIR required")
endif()
file(MAKE_DIRECTORY "${TEST_OUTPUT_DIR}")
file(READ "${SOURCE_DIR}/presets/shots/reference.json" fixture)
# One scene shared with the existing legacy contract, small real GPU requests.
string(JSON fixture SET "${fixture}" shots 0 width 64)
string(JSON fixture SET "${fixture}" shots 0 height 36)
string(JSON fixture SET "${fixture}" shots 1 width 64)
string(JSON fixture SET "${fixture}" shots 1 height 36)
set(scene "${TEST_OUTPUT_DIR}/scene.json")
file(WRITE "${scene}" "${fixture}")
string(JSON preset GET "${fixture}" scene preset)
file(WRITE "${TEST_OUTPUT_DIR}/preset.json" "${preset}")

function(fails name expected)
    set(output "${TEST_OUTPUT_DIR}/${name}.png")
    file(REMOVE "${output}")
    execute_process(COMMAND "${CLI}" ${ARGN} --output "${output}"
        WORKING_DIRECTORY "${TEST_OUTPUT_DIR}"
        RESULT_VARIABLE status OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    if(status EQUAL 0 OR EXISTS "${output}" OR NOT stderr MATCHES "${expected}")
        message(FATAL_ERROR "${name}: expected '${expected}', status=${status}, got ${stdout}${stderr}")
    endif()
endfunction()
function(render name)
    file(REMOVE "${TEST_OUTPUT_DIR}/${name}.png")
    execute_process(COMMAND "${CLI}" ${ARGN} --output "${TEST_OUTPUT_DIR}/${name}.png"
        WORKING_DIRECTORY "${TEST_OUTPUT_DIR}"
        RESULT_VARIABLE status OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    if(NOT status EQUAL 0 OR NOT EXISTS "${TEST_OUTPUT_DIR}/${name}.png")
        message(FATAL_ERROR "${name}: status=${status}, ${stdout}${stderr}")
    endif()
    if(NOT stderr MATCHES "Rendering 64x36")
        message(FATAL_ERROR "${name}: dimensions not applied: ${stderr}")
    endif()
    if(NOT name STREQUAL "legacy" AND NOT stderr MATCHES "Shot .*frame=.*time=.*duration=")
        message(FATAL_ERROR "${name}: timeline metadata absent: ${stderr}")
    endif()
endfunction()

fails(incomplete_file "required together" --shot-file "${scene}")
fails(incomplete_id "required together" --shot-id fixed)
fails(incomplete_frame "required together" --frame 0)
fails(incomplete_file_id "required together" --shot-file "${scene}" --shot-id fixed)
fails(incomplete_file_frame "required together" --shot-file "${scene}" --frame 0)
fails(incomplete_id_frame "required together" --shot-id fixed --frame 0)
set(selection --shot-file "${scene}" --shot-id fixed --frame 0)
foreach(option "--params;anything" "--spin;0.9" "--resolution;64x36" "--no-starfield" "--starfield;missing.exr" "--integrator;rk45")
    string(MAKE_C_IDENTIFIER "${option}" name)
    fails("mixed_${name}" "incompatible" ${selection} ${option})
endforeach()
foreach(option "--shot-file;anything" "--shot-id;fixed" "--frame;0" "--output;unused.png")
    string(MAKE_C_IDENTIFIER "${option}" name)
    fails("duplicate_${name}" "only be specified once" ${selection} ${option})
endforeach()
fails(missing_value "Missing value" --shot-file --shot-id fixed --frame 0)
fails(unknown_id "Unknown shot ID" --shot-file "${scene}" --shot-id absent --frame 0)
foreach(index -1 1junk 1.5 18446744073709551616)
    fails("bad_frame_${index}" "nonnegative integer" --shot-file "${scene}" --shot-id fixed --frame "${index}")
endforeach()
fails(out_of_range "Frame index outside" --shot-file "${scene}" --shot-id fixed --frame 180)
fails(overflow_frame "Frame index outside" --shot-file "${scene}" --shot-id fixed --frame 18446744073709551615)
fails(missing_file "Cannot open cinematic" --shot-file "${TEST_OUTPUT_DIR}/missing.json" --shot-id fixed --frame 0)
string(JSON enabled SET "${fixture}" scene preset enable_starfield true)
string(JSON enabled SET "${enabled}" scene starfield_exr "\"assets/sky.exr\"")
file(WRITE "${TEST_OUTPUT_DIR}/enabled.json" "${enabled}")
file(REMOVE "${TEST_OUTPUT_DIR}/assets/sky.exr")
fails(missing_asset "Required starfield.*assets/sky.exr" --shot-file enabled.json --shot-id fixed --frame 0)
file(MAKE_DIRECTORY "${TEST_OUTPUT_DIR}/assets")
file(WRITE "${TEST_OUTPUT_DIR}/assets/sky.exr" "not an EXR")
fails(invalid_asset "Failed to load starfield" --shot-file enabled.json --shot-id fixed --frame 0)
file(WRITE "${TEST_OUTPUT_DIR}/bad.json" "{")
fails(malformed "Error:" --shot-file bad.json --shot-id fixed --frame 0)
render(legacy --params "${TEST_OUTPUT_DIR}/preset.json" --resolution 64x36)
render(fixed --shot-file scene.json --shot-id fixed --frame 0)
render(fixed_last --shot-file scene.json --shot-id fixed --frame 179)
render(fixed_repeat --shot-file scene.json --shot-id fixed --frame 0)
file(SHA256 "${TEST_OUTPUT_DIR}/legacy.png" expected)
foreach(name fixed fixed_last fixed_repeat)
    file(SHA256 "${TEST_OUTPUT_DIR}/${name}.png" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "${name}: fixed frame must match legacy PNG bytes")
    endif()
endforeach()
foreach(index 0 300 599)
    render("orbit_${index}" --shot-file scene.json --shot-id orbit --frame ${index})
    file(SHA256 "${TEST_OUTPUT_DIR}/orbit_${index}.png" hash_${index})
endforeach()
if(hash_0 STREQUAL hash_300 OR hash_0 STREQUAL hash_599 OR hash_300 STREQUAL hash_599)
    message(FATAL_ERROR "Moving radial/inclination samples must change the rendered image")
endif()
message(STATUS "Shot CLI rejection, relative assets, exact fixed parity and distinct orbit samples passed")
