file(MAKE_DIRECTORY "${TEST_OUTPUT_DIR}/assets")
file(COPY "${SOURCE_DIR}/presets/cinematic/assets/stars-v1.exr" DESTINATION "${TEST_OUTPUT_DIR}/assets")
file(READ "${SOURCE_DIR}/presets/cinematic/scene.json" fixture)
foreach(index 0 1)
    string(JSON fixture SET "${fixture}" shots ${index} width 64)
    string(JSON fixture SET "${fixture}" shots ${index} height 36)
endforeach()
file(WRITE "${TEST_OUTPUT_DIR}/scene.json" "${fixture}")
foreach(name fixed repeat orbit)
    set(shot fixed)
    set(frame 0)
    if(name STREQUAL orbit)
        set(shot orbit)
        set(frame 300)
    endif()
    execute_process(COMMAND "${CLI}" --shot-file scene.json --shot-id ${shot} --frame ${frame} --output ${name}.png
        WORKING_DIRECTORY "${TEST_OUTPUT_DIR}" RESULT_VARIABLE result ERROR_VARIABLE error TIMEOUT 30)
    if(NOT result EQUAL 0 OR NOT error MATCHES "Cinematic v2.*invalid=0")
        message(FATAL_ERROR "Cinematic CLI: ${result}: ${error}")
    endif()
    file(SHA256 "${TEST_OUTPUT_DIR}/${name}.png" hash_${name})
    file(READ "${TEST_OUTPUT_DIR}/${name}.png" chunk OFFSET 37 LIMIT 5 HEX)
    if(NOT chunk STREQUAL "7352474200")
        message(FATAL_ERROR "Missing cinematic sRGB chunk: ${chunk}")
    endif()
endforeach()
if(NOT hash_fixed STREQUAL hash_repeat OR hash_fixed STREQUAL hash_orbit)
    message(FATAL_ERROR "Cinematic fixed determinism or moving-frame change failed")
endif()
# Invalid v2 must not fall back, write output, or replace an existing good PNG.
string(JSON bad SET "${fixture}" appearance tone_map "\"unrecognized\"")
file(WRITE "${TEST_OUTPUT_DIR}/bad.json" "${bad}")
execute_process(COMMAND "${CLI}" --shot-file bad.json --shot-id fixed --frame 0 --output fixed.png
    WORKING_DIRECTORY "${TEST_OUTPUT_DIR}" RESULT_VARIABLE result ERROR_VARIABLE error TIMEOUT 30)
file(SHA256 "${TEST_OUTPUT_DIR}/fixed.png" preserved)
if(result EQUAL 0 OR NOT preserved STREQUAL hash_fixed OR NOT error MATCHES "Unsupported appearance")
    message(FATAL_ERROR "Invalid v2 was not rejected transactionally: ${error}")
endif()
string(JSON bad SET "${fixture}" scene starfield_exr "\"missing.exr\"")
file(WRITE "${TEST_OUTPUT_DIR}/bad.json" "${bad}")
execute_process(COMMAND "${CLI}" --shot-file bad.json --shot-id fixed --frame 0 --output fixed.png
    WORKING_DIRECTORY "${TEST_OUTPUT_DIR}" RESULT_VARIABLE result ERROR_VARIABLE error TIMEOUT 30)
file(SHA256 "${TEST_OUTPUT_DIR}/fixed.png" preserved)
if(result EQUAL 0 OR NOT preserved STREQUAL hash_fixed OR NOT error MATCHES "Required starfield")
    message(FATAL_ERROR "Missing relative sky was not rejected: ${error}")
endif()
